dependencies:
  artemis:
    url: github.com/toitware/toit-artemis
    version: ^0.4.0
  dns_simple_server:
    url: github.com/toitlang/pkg-dns-simple-server
    version: ^0.2.1
  http:
    url: github.com/toitlang/pkg-http
    version: ^1.9.3
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
