dependencies:
  dns_simple_server:
    url: github.com/toitlang/pkg-dns-simple-server
    version: ^0.2.1
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.5.0
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
